sheduler:
  serviceAccountName: mysql-scheduler-sa
  image: "oilerbackup/mysql-scheduler:0.0.1"
  imagePullPolicy: Always
  name: mysql-scheduler
  namespace: oiler-backup-system
  port: 50051
  replicas: 1
backuper:
  image: "oilerbackup/mysql-backuper:0.0.1"
restorer:
  image: "oilerbackup/mysql-restorer:0.0.1"